{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-ch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-ch-exporter.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "prometheus-ch-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
